Shop/src/com/cn/shop/model/Cart.java
package com.cn.shop.model;

import java.util.HashMap;
import java.util.Map;

import org.apache.log4j.Logger;

//购物车
public class Cart {
	
	//定义一个日志
	private Logger logger = Logger.getLogger(this.getClass());
	
	//产品id 项目记录
	private Map< Long, Item > items = new HashMap<Long, Item >( );
	
	//添加商品到购物车
	
	public  void addItem( Product product , int number )
	{
		if( items.containsKey(product.getId()))
		{
			return;
		}
		Item item = new Item( number, product );
		
		items.put(product.getId(),  item );
		
	}
	
	//修改商品数量
	public void modifyNumberBYProductId( long productId, int number )
	{
		Item item = items.get(productId);
		
		item.setNumber(number);
		
	}
	
	//删除商品项目
	
	public void deleteItemByProductId( long productId )
	{
		items.remove(productId);
		
	}

	//删除多个商品项目
	
	public void deleteItemByProductId( Long [] productIds )
	{
		for( Long id : productIds )
		{
			items.remove(id );
		}
	}
	
	
	//清空购物车
	
	public void clear( )
	{
		items.clear();
		
		logger.info("Cart cleared. size="+ items.size() );
		
	}
	
	//获得所有项目
	
	
	public  Map<Long , Item > getCartItems( )
	{
		return items;
		
	}
	
	//购得购物车项目的数目
	
	public int getItemNumber( )
	{
		return items.size();
	}
	
	//判断购物车是否为空
	public boolean isEmpty( )
	{
		return items.isEmpty();
		
	}
	
	//购物车所有商品的总价
	
	public Double getPrice( )
	{
		double sum = 0;
		
		for( Long id : items.keySet() )
		{
			Item item = items.get(id);
			
			sum+=item.getCost();
			
		}
		
		return sum;
	}

	public Map<Long, Item> getItems() {
		return items;
	}

	public void setItems(Map<Long, Item> items) {
		this.items = items;
	}
	
	
	
	
}

Shop/src/com/cn/shop/model/Order.java
package com.cn.shop.model;

import java.util.HashMap;
import java.util.Map;




import com.cn.shop.common.Constants;


public class Order {
	
	private Long id; //主键
	
	private String orderNum; //订单号
	
	private Integer status; //订单状态
	
	private User user; //所属用户
	
	private Double cost; //总价
	
	private Map<Long,Item > items = new HashMap<Long, Item >( ); //包含的订单项，产品id为key

	public Order() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	//传递状态值、所属用户的构造方法
	public Order( Integer status , User user )
	{
		super( );
		
		this.status = status;
		
		this.user = user;
		
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}


	
	public Integer getStatus( ) {
		return  status;
	}
	
/*	public String  getStatus( ) {
		
		String text = null;
		switch (status) {
		case Constants.ORDER_STATUS_POST:
			text = "订单已提交";
			break;
		case Constants.ORDER_STATUS_SEND:
			text = "已发货";
			break;
		case Constants.ORDER_STATUS_RECEIVE:
			text = "用户已收货";
			break;
		case Constants.ORDER_STATUS_END:
			text = "订单完成";
			break;
		default:
			break;
		}
		return text;
	 
	}
	 */
	

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Double getCost() {
		
		double sum = 0;
		
		for( Long id : items.keySet() )
		{
			Item item = items.get(id);
			
			sum += item.getCost();
		}
		
		this.cost = sum;
		return cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Map<Long, Item> getItems() {
		return items;
	}

	public void setItems(Map<Long, Item> items) {
		this.items = items;
	}
	
	
	
	

}

Shop/src/com/cn/shop/action/CartAction.java
package com.cn.shop.action;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts2.ServletActionContext;

import com.cn.shop.common.Constants;
import com.cn.shop.model.Cart;
import com.cn.shop.model.Item;
import com.opensymphony.xwork2.ActionSupport;

public class CartAction  extends  ActionSupport  {
	
	private Logger logger = Logger.getLogger(this.getClass());
	
	private HttpServletRequest request ;

	private HttpSession session ;
	

	
	//来到购物车主页面
	
	public String CartIndex( )
	{
		
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		
		Cart cart = (Cart) this.session.getAttribute( Constants.SESSION_CART);
		
		if( cart == null )
		{
			cart = new Cart( );
			
			this.session.setAttribute(Constants.SESSION_CART, cart );
		}
		
		
		return "cart";
		
		
	}
	
	//修改购物车里添加商品项的数量
	public String modifyItemNumber( )
	{
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		
		
		String [] itemCheck =  this.request.getParameterValues("itemCheck");
		
		if( itemCheck == null || itemCheck.length == 0 )
		{
			return "cart";
		}
		else
		{
			Cart cart = ( Cart ) this.session.getAttribute(Constants.SESSION_CART);
			
			for( String productId : itemCheck )
			{
				String number = this.request.getParameter("number"+productId);
				
				cart.modifyNumberBYProductId(Long.valueOf(productId),  Integer.valueOf(number));
			}
			
			for( Long id : cart.getCartItems().keySet() )
			{
				Item it = cart.getCartItems().get(id);
				
				System.out.println( it.getProduct().getName() + " " + it.getNumber() );
			}
		
			return "cart";
		}
	}
	
	//删除购物车的商品项目
	
	public String deleteItem( )
	{
	
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		
		String []  itemCheck = this.request.getParameterValues("itemCheck");
		
		if( itemCheck == null || itemCheck.length == 0 )
		{
			return "cart";
		}
		else
		{
			logger.info("Deleting item size="+itemCheck.length );
			
			Long [ ] productIds = new Long[ itemCheck.length ];
			
			for( int i = 0; i < productIds.length; i++ )
			{
				productIds[ i ] = Long.valueOf(itemCheck[i]);
				
				
			}
			
			Cart cart = ( Cart ) this.session.getAttribute(Constants.SESSION_CART );
			
			cart.deleteItemByProductId(productIds);
			
			for( Long id : cart.getCartItems().keySet() )
			{
				Item it = cart.getCartItems().get(id);
				
				System.out.println( it.getProduct().getName() + " " + it.getNumber() );
			}
			
			return "cart";
		}
		
	}
	
	//清空购物车页面
	public String clear( )
	{
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		
		logger.info("Cart is clearing...");
		
		Cart cart = ( Cart ) this.session.getAttribute(Constants.SESSION_CART );
		
		cart.clear();
		
		for( Long id : cart.getCartItems().keySet() )
		{
			Item it = cart.getCartItems().get(id);
			
			System.out.println( it.getProduct().getName() + " " + it.getNumber() );
		}
		
		return "cart";
	}
	
	
	

}

Shop/src/com/cn/shop/action/FindAction.java
package com.cn.shop.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts2.ServletActionContext;

import com.cn.shop.model.Product;
import com.cn.shop.service.ProductService;
import com.cn.shop.util.FenciUtil;
import com.cn.shop.util.WordFilter;
import com.opensymphony.xwork2.ActionSupport;

public class FindAction  extends ActionSupport {
	
	//商品service IOC
	private ProductService productService;
	
	//搜索关键字
	private String keyword;
	
	//搜索结果上篇链表
	
	private List< Product > findlist;
	
	//搜索分页
	
	private int page;
	 
	 private int maxpage;
	
	private HttpServletRequest request;
	
	
	
	public int getPage() {
		return page;
	}



	public void setPage(int page) {
		this.page = page;
	}



	public int getMaxpage() {
		return maxpage;
	}



	public void setMaxpage(int maxpage) {
		this.maxpage = maxpage;
	}



	public String getKeyword() {
		return keyword;
	}



	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	
	
	

	public ProductService getProductService() {
		return productService;
	}



	public void setProductService(ProductService productService) {
		this.productService = productService;
	}



	public List<Product> getFindlist() {
		return findlist;
	}



	public void setFindlist(List<Product> findlist) {
		this.findlist = findlist;
	}



	//商品的搜索
	public String findproduct( )
	{
			if( keyword == null )
			{
				return "restart";
			}
		
			System.out.println("关键字"+keyword);
		
				//分词链表
				List<String> keylist = new ArrayList<String>();
				
				//过滤器配置文件的filtermap
				
				 Map<String,String > filtermap = new HashMap<String ,String >( );
				
				
				//提取关键字的keymap
				 
				 Map<String , String > keymap = new HashMap<String, String >( );
				 
				 //关键字
				 
				 String word = null;
				 
				 //配置文件地址
				 
				 String url  = ServletActionContext.getServletContext().getRealPath("/WEB-INF/classes/filter.dic") ;  
						 
							 
				 System.out.println( url  );
				 
				 
				 
				 
				 try {
					 
					 //1、进行分词
					 FenciUtil.fenci(keyword, keylist  );
					
					for( int i = 0 ; i < keylist.size() ; i++ )
						
					{
						System.out.println( keylist.get(i) );
					}
					
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
				
				//2、读过滤器配置文件 指定配置文件url
				 
				 WordFilter.readType(filtermap , url   );
				 
				 for( String key : filtermap.keySet() )
				 {
					 
					 System.out.println("key" + key + "value" + filtermap.get(key));
				 }
				 
				 //3、提取关键字
				 
				 for( int i = 0 ; i < keylist.size(); i++ )
				 {
					 //获取关键字
					 word = keylist.get(i);
					 
					 //提取关键字
					 
					 WordFilter.filterword(word, filtermap, keymap);
					 
					 
					 
				 }
				 
				 //最后查看 keymap
				 
				 System.out.println("=====================");
				 
				 for( String key : keymap.keySet() )
				 {
					 
					 System.out.println("key" + key + "value" + keymap.get(key));
				 }
				 
				

				 this.request = ServletActionContext.getRequest();
					
					int maxpage = this.productService.findnum(keymap);
					
					int pageNo  =1;
					
					int pageSize = 5;
					
					if( page >  0 )
					{
						pageNo = page;
					}
					
					
					findlist = this.productService.find(keymap, pageNo, pageSize);
					
					//与list.jsp页面page和  maxpage  重复导致换乱  bug
					
					request.setAttribute("fpage", pageNo);
					
					request.setAttribute("fmaxpage", maxpage);
		
		
					System.out.println( "大小" + findlist.size() );
		
		
		
		

		
					return "success";
	}
	

}

Shop/src/com/cn/shop/action/ListAction.java
package com.cn.shop.action;

import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts2.ServletActionContext;

import com.cn.shop.common.Constants;
import com.cn.shop.model.Cart;
import com.cn.shop.model.Product;
import com.cn.shop.service.ProductService;
import com.cn.shop.service.UserService;

import com.opensymphony.xwork2.ActionSupport;

public class ListAction extends ActionSupport {
	
	//商品service IOC
	private ProductService productService;
	
	//商品链表
	private List< Product > productlist;
	
	//获的商品ID
	private Long productId;
	
	private UserService userService;
	
	private HttpServletRequest request;
	
	private HttpServletResponse response;

	private HttpSession session;
	
	 private ServletContext application;
	 
	 //显示图片 2014.8.28
	 
	 //传输时缩小图片大小
	 
/*	private  String imageUrl;

	
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
*/
	 //添加分页 
	 
	 private int page;
	 
	 private int maxpage;
	 
	 // type参数 区别 list.jsp 和findlist.jsp页面 2014.8.31
	 
	 /*通过type == 1 来区别 list.jsp 和findlist.jsp页面, type== 1,跳到findlist.jsp页面*/
	 
	 private int type;
	 
	 
	 
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	// page maxpage 放入request 
	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	
	
	public int getMaxpage() {
		return maxpage;
	}

	public void setMaxpage(int maxpage) {
		this.maxpage = maxpage;
	}

	public ProductService getProductService() {
		return productService;
	}

	public void setProductService(ProductService productService) {
		this.productService = productService;
	}

	public List<Product> getProductlist() {
		return productlist;
	}

	public void setProductlist(List<Product> productlist) {
		this.productlist = productlist;
	}
	
	
	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/*public String list( )
	{
		productlist = this.productService.getALLProducts();
		
		return"list";
	}*/
	
	//添加分页显示2014.8.19
	
	public String list( )
	{
		this.request = ServletActionContext.getRequest();
		
		int maxpage = this.productService.maxSize();
		
		int pageNo  =1;
		
		int pageSize = 5;
		
		if( page >  0 )
		{
			pageNo = page;
		}
		
		
		productlist = this.productService.getByPage(pageNo , pageSize );
		
		request.setAttribute("page", pageNo);
		
		request.setAttribute("maxpage", maxpage);
		
		return"list";
	}
	
		
	
	public  String addItem( )
	{
		String ret = "add";
		
		System.out.println(productId);
		
		Product product = this.productService.getProduct(productId);
		
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		
		Cart cart = (Cart) this.session.getAttribute( Constants.SESSION_CART);
		
		if( cart == null )
		{
			cart = new Cart( );
			
			this.session.setAttribute(Constants.SESSION_CART, cart );
		}
		
		cart.addItem(product, 1);
		
		System.out.println( cart.getPrice() );
		
		//System.out.println("type:" + type );
		
		
		if( type == 1 )
		{
			ret ="find";
			
			//2014。8.31 bug  获取type后注意恢复
			
			type = 0;
		}
		
		return ret;
	}
	//传输时缩小图片大小
	
	/*public void showImage( )
	{
		
		
		request = ServletActionContext.getRequest();
		
		response = ServletActionContext.getResponse();
		
		String url = imageUrl.substring(0, imageUrl.length() -3 );
		
		com.cn.shop.util.ZipImage.zip(request, response, url );
	}
	*/

}

Shop/src/com/cn/shop/action/LoginAction.java
package com.cn.shop.action;

import javax.annotation.Resource;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts2.ServletActionContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.cn.shop.common.Constants;
import com.cn.shop.model.Administrator;
import com.cn.shop.model.User;
import com.cn.shop.service.UserService;
import com.opensymphony.xwork2.ActionSupport;


public class LoginAction  extends ActionSupport {
	
	private String username;
	
	private String password;
	
	private UserService userService;
	
	private HttpServletRequest request;

	private HttpSession session;
	
	 private ServletContext application;

	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}



	

	public UserService getUserService() {
		return userService;
	}


	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	@Override
	public String execute() throws Exception {
		// TODO Auto-generated method stub
		
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();

		 

		
		String ret="";
		
		User user = this.userService.login(username, password);
		
		if( user == null )
		{
			this.request.setAttribute("msg", "登录失败");
			
			ret="restart";
			
		}
		else
		{
			this.session.setAttribute(Constants.SESSION_USER, user );
			
			//判断是否为管理员，若是跳到后台
			
			if( user instanceof Administrator )
			{
				ret = "manager";
			}
			else
			{
			
				ret="user";
			}
		}
		
		return ret;
		
	}
	
	
	
	

}

Shop/src/com/cn/shop/action/OrderAction.java
package com.cn.shop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts2.ServletActionContext;

import com.cn.shop.common.Constants;
import com.cn.shop.model.Cart;
import com.cn.shop.model.Order;
import com.cn.shop.model.User;
import com.cn.shop.service.OrderService;
import com.opensymphony.xwork2.ActionSupport;

//订单Action
public class OrderAction extends ActionSupport {
	
	private OrderService orderService;

	public OrderService getOrderService() {
		return orderService;
	}

	public void setOrderService(OrderService orderService) {
		this.orderService = orderService;
	}
	
	private HttpServletRequest request ;

	private HttpSession session ;
	
	
	//订单主页
	public String index( )
	{
		String ret = "";
		
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		 
		 User user = (User)this.session.getAttribute(Constants.SESSION_USER);
			
		 if( user == null )
		 {
			 ret ="login";
		 }
		 else
		 {
			 ret ="order";
		 }
		
		return ret;
	}
	
	//提交订单
	public String postOrder( )
	{
		
		this.request = ServletActionContext.getRequest();

		 this.session = this.request.getSession();
		 
		 User user = (User)this.session.getAttribute(Constants.SESSION_USER);
		 
		 Cart cart = ( Cart )this.session.getAttribute(Constants.SESSION_CART);
		 
		 Order order = new Order( );
		 
		 order.setUser(user);
		 
		 order.setItems( cart.getItems() );
		 
		 order.setStatus( Constants.ORDER_STATUS_POST );
		 
		 //调用业务层，产生新订单
		 
		 String orderNum = orderService.generateOrder(order);
		 
		 this.request.setAttribute(Constants.REQ_ORDER_NUMBER, orderNum );
		 
		
		return "success";
	}

}

Shop/WebContent/Test.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
		Hello Shop!!!!
</body>
</html>

Shop/WebContent/cart.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<% String context = request.getContextPath(); %>

<%@taglib uri="/struts-tags" prefix="s" %>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>我的购物车</title>
<SCRIPT language=javascript>
			function clearCart(){
				cartForm.action="cart_clear?method=clear";
				cartForm.submit();
			}
			function deleteCartItem(){
				cartForm.action="cart_delete?method=deleteItem";
				cartForm.submit();
			}
		
			function modifyNumber(){
				cartForm.action="cart_modify?method=modifyItemNumber";
				cartForm.submit();
			}
		</SCRIPT>
</head>
<body>
		<H1 align=center>
			购物车
		</H1>
		<FORM name=cartForm action="<%=context %>/from/listaction!list" method=post>
			<input type="hidden" name="method" value="index" />
			<TABLE cellSpacing=0 cellPadding=0 width="75%" align=center border=1>
				<TBODY>
					<TR align=middle>
						<TD width="7%">
							选择
						</TD>
						<TD width="21%" height=30>
							商品名称
						</TD>
						<TD width="14%" height=30>
							单价
						</TD>
						<TD width="25%" height=30>
							数量
						</TD>
						<TD width="33%" height=30>
							合计
						</TD>
					</TR>
					<c:forEach var="item" items="${sessionScope.cart.items}">
						<TR align=middle>
							<TD height=30>
								<INPUT type=checkbox value=${item.key } name=itemCheck>
							</TD>
							<TD height=30>
								${item.value.product.name}
							</TD>
							<TD height=30>
								${item.value.product.price}
							</TD>
							<TD height=30>
								<INPUT maxLength=10 size=10 value=${item.value.number
									} name="number${item.key}">
							</TD>
							<TD height=30>
								${item.value.cost}
							</TD>
						</TR>
					</c:forEach>
					<TR>
						<TD colSpan=5 height=30>
							您的购物车中所有商品总金额：${sessionScope.cart.price }
						</TD>
					</TR>
				</TBODY>
			</TABLE>
			<BR>
			<BR>
			<TABLE cellSpacing=0 cellPadding=0 width=450 align=center border=0>
				<TBODY>
					<TR align=middle>
						<TD width="22%">
							<INPUT onclick=modifyNumber() type=button value=修改所选项的数量
								name=Button>
						</TD>
						<TD width="20%">
							<INPUT onclick=deleteCartItem() type=button value=删除所选项
								name=Submit2>
						</TD>
						<TD width="26%">
							<INPUT onclick="clearCart();" type=button value=清空购物车
								name=Submit3>
						</TD>
						<TD width="12%">
							<INPUT
								onclick="javascript:location.href='order_index?method=index'"
								type=button value=结账 name=Submit42>
						</TD>
						<TD width="20%">
							<INPUT
								onclick="javascript:location.href='listaction?method=list'"
								type=button value=继续购物 name=Submit42>
						</TD>
					</TR>
				</TBODY>
			</TABLE>
			<P align=center>
				&nbsp;
			</P>
		</FORM>
	

</body>
</html>

Shop/WebContent/fail.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	
	Fail!!!!

</body>
</html>

Shop/WebContent/order.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<% String context = request.getContextPath(); %>

<%@taglib uri="/struts-tags" prefix="s" %>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>我的购物车</title>
</head>
<body>

	<H1 align=center>
			你所购买的商品如下：
		</H1>
		<TABLE cellSpacing=0 cellPadding=0 width="75%" align=center border=1>
			<TBODY>
				<TR align=middle>
					<TD width="21%" height=30>
						商品名称
					</TD>
					<TD width="14%" height=30>
						单价
					</TD>
					<TD width="25%" height=30>
						数量
					</TD>
					<TD width="33%" height=30>
						合计
					</TD>
				</TR>
				<c:forEach var="item" items="${sessionScope.cart.items}">
					<TR align=middle>
						<TD height=30>
							${item.value.product.name }
						</TD>
						<TD height=30>
							${item.value.product.price }
						</TD>
						<TD height=30>
							${item.value.number }
						</TD>
						<TD height=30>
							${item.value.cost }
						</TD>
					</TR>
				</c:forEach>
				<TR>
					<TD colSpan=5 height=30>
						您的购物车中所有商品总金额：${sessionScope.cart.price }
					</TD>
				</TR>
			</TBODY>
		</TABLE>
		<P>
		<H1 align=center>
			用户联系方式如下：
		</H1>
		<P></P>
		<form action="<%=context %>/from/cart_post!postOrder" method="post">
			<!-- <html:hidden property="method" value="postOrder" /> -->
			<TABLE cellSpacing=0 cellPadding=0 width=500 align=center border=0>
				<TBODY>
					<TR>
						<TD width=117 height=23>
							姓名：
						</TD>
						<TD width=383>
							<INPUT value="${sessionScope.user.name }" name="name">
						</TD>
					</TR>
					<TR>
						<TD height=24>
							地址：
						</TD>
						<TD>
							<INPUT value="${sessionScope.user.address }" name="address">
						</TD>
					</TR>
					<TR>
						<TD height=24>
							邮政编码：
						</TD>
						<TD>
							<INPUT value="${sessionScope.user.postCode }" name="postCode">
						</TD>
					</TR>
					<TR>
						<TD height=23>
							E-mail：
						</TD>
						<TD>
							<INPUT value="${sessionScope.user.email }" name="email">
						</TD>
					</TR>
					<TR>
						<TD height=23>
							联系电话：
						</TD>
						<TD>
							<INPUT value="${sessionScope.user.cellPhone }" name="phone">
						</TD>
					</TR>
				</TBODY>
			</TABLE>
			<BR>
			<TABLE cellSpacing=0 cellPadding=0 width=500 align=center border=0>
				<TBODY>
					<TR>
						<TD align=middle>
							<!-- <INPUT type=submit value=结帐 name=Submit> -->
							<input type="submit" value="结帐">
						</TD>
						<TD align=middle>
							<INPUT
								onclick="javascript:location.href='listaction?method=list'"
								type=button value="继续购物" name=Submit42>
						</TD>
						<TD align=middle>
							<INPUT
								onclick="javascript:location.href='cart_inedx?method=CartIndex'"
								type=button value="回到购物车" name=Submit42>
						</TD>
					</TR>
				</TBODY>
			</TABLE>
		</form>

</body>
</html>